name: Terraform Apply
description: Intializes and applies a Terraform configuration
author: Synthetik Technologies

inputs:
  tf_path:
    description: Path to the Terraform configuration
    required: true
  tf_vars:
    description: Variables to pass to Terraform
    required: false
    default: ""
  tf_api_token:
    description: Terraform API token
    required: true

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ inputs.tf_api_token }}

    - uses: actions/checkout@v3

    - name: Terraform Init
      shell: bash
      run: terraform init
      working-directory: ${{ github.workspace }}/${{ inputs.tf_path }}

    - name: Terraform Apply
      shell: bash
      if: inputs.tf_vars != ''
      run: terraform apply -auto-approve -input=false -var=${{ inputs.tf_vars }}
      working-directory: ${{ github.workspace }}/${{ inputs.tf_path }}

    - name: Terraform Apply
      shell: bash
      if: inputs.tf_vars == ''
      run: terraform apply -auto-approve -input=false
      working-directory: ${{ github.workspace }}/${{ inputs.tf_path }}
