name: Short SHA Versioning

author: Synthetik Technologies

description: Handles versioning by getting the most recent commit sha

outputs:
  version:
    description: Short sha of the most recent commit
    value: ${{ steps.get-short-sha.outputs.version }}

runs:
  using: composite
  steps:
    - name: Get Short SHA
      shell: bash
      id: get-short-sha
      run: |
        if ${{ github.event_name }} == 'pull_request'; then
           sha=${{ github.event.pull_request.head.sha }}
        else
           sha=${{ github.sha }}
        fi
        echo "::set-output name=version::$(echo ${sha::7})" #* shortens sha
