name: Short SHA Versioning

author: Synthetik Technologies

description: Handles versioning by getting the most recent commit sha

outputs:
   version:
    description: Short sha of the most recent commit
    value: ${{ steps.get-short-sha.outputs.version }}

runs:
  using: "composite"
  steps:
  - name: Get Short SHA
    shell: 'bash'
    id: get-short-sha
    run: |
      version=${{ github.event.pull_request.head.sha }}
      echo "::set-output name=version::$(echo ${version::7})" #* shortens sha