name: Build and Push Docker Image
description: Build and (optionally) push Docker images
author: Synthetik Technologies
inputs:
  image-name:
    description: Name of the image to build
    required: true
  registry:
    description: Registry to push to. If no registry is provided, image will not be pushed
    required: false
    default: ""
  version:
    description: Image version; if no version is provided, the image will be tagged "latest"
    required: false
    default: "latest"
  registry-password:
    description: Password for the registry
    required: false
    default: ""
  supporting-ssh-key:
    description: Path to the supporting ssh key. Used for accessing additional private repositories.
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Get image name with tag
      shell: bash
      run: |
        image=${{ inputs.registry }}${{ inputs.image-name }}:${{ inputs.version }}
        echo "FULLIMAGE=$image" >> $GITHUB_ENV
    - name: Setup Qemu
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        ssh: default=${{ env.SSH_AUTH_SOCK }}
        push: true
        tags: ${{ env.FULLIMAGE }}
        platforms: linux/arm64
        cache-from: type=gha
        cache-to: type=gha, mode=max
