name: Build and Push Docker Image
description: Build and (optionally) push Docker images
author: Synthetik Technologies
inputs:
  image-name:
    description: The full image name, including repository and version
    required: true
  platforms:
    description: Platforms/architectures to build for. Defaults to AMD64
    required: false
    default: "linux/amd64"

runs:
  using: composite
  steps:
    - name: Setup Qemu
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        ssh: default=${{ env.SSH_AUTH_SOCK }}
        push: true
        tags: ${{ inputs.image-name }}
        platforms: ${{ inputs.platforms }}
        cache-from: type=gha
        cache-to: type=gha, mode=max
