name: Semantic Version
description: Semantic versioning
author: Synthetik Technologies

inputs:
  github_token:
    description: GitHub token
    required: true
outputs:
  version:
    description: The semantic version
    value: ${{ steps.create-release.outputs.version }}

runs:
  using: composite
  steps:
    - name: Checkout Branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "lts/*"

    - name: Install dependencies
      shell: bash
      run: npm install semantic-release @semantic-release/exec @semantic-release/git

    - name: Create Release
      id: create-release
      shell: bash
      run: |
        npx semantic-release
        echo "::set-output name=version::$(echo ${{ env.VERSION }})"
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
