name: Semantic Version
description: Semantic versioning
author: Synthetik Technologies

inputs:
  github_token:
    description: GitHub token
    required: true
outputs:
  version:
    description: The semantic version
    value: ${{ steps.get-semantic-version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Checkout Branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "lts/*"

    - name: Install dependencies
      shell: bash
      run: npm install semantic-release @semantic-release/exec

    - name: Create Release
      shell: bash
      run: |
        npx semantic-release
        echo "outputs:
          version: ${{ steps.get-semantic-version.outputs.version }}"
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
