name: Actions Repo Versioning

on:
  push:
    branches:
      - master
      - main
      - develop

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    steps:
      - name: Version
        uses: synthetik-technologies/actions/composites/semantic-versioning@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
