name: Module Deployment

on:
  workflow_call:
    inputs:
      image-name: # Unless I make this an artifact
        required: true
        type: string
    secrets:
      DEV_CONTAINER_REGISTRY_PASSWORD:
        required: true
      PROD_CONTAINER_REGISTRY_PASSWORD:
        required: true
      SYNTHETIKDEV_UVIS_IOT_HUB_CSTRING:
        required: true
      

jobs:
  module-cd:
    runs-on: ubuntu-latest
    steps:
      #* Login
      - name: Log into develop container registry
        uses: docker/login-action@v1
        with:
          registry: synthetikdev.azurecr.io
          username: synthetikDev
          password: ${{ secrets.DEV_CONTAINER_REGISTRY_PASSWORD }}
      - name: Log into production container registry
        uses: docker/login-action@v1
        with:
          registry: synthetik.azurecr.io
          username: synthetik
          password: ${{ secrets.PROD_CONTAINER_REGISTRY_PASSWORD }}
      - name: Log into Azure IoT Hub
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SYNTHETIKDEV_UVIS_IOT_HUB_CSTRING }}

      