name: Module Deployment

on:
  workflow_call:
    inputs:
      image-name: # Unless I make this an artifact
        required: true
        type: string
      labels:
        required: true
        type: string
    secrets:
      DEV_CONTAINER_REGISTRY_PASSWORD:
        required: true
      PROD_CONTAINER_REGISTRY_PASSWORD:
        required: true
      SYNTHETIKDEV_UVIS_IOT_HUB_CSTRING:
        required: true
      

jobs:
  module-cd:
    runs-on: ubuntu-latest
    steps:
      #* Login
      - name: Log into develop container registry
        uses: docker/login-action@v1
        with:
          registry: synthetikdev.azurecr.io
          username: synthetikDev
          password: ${{ secrets.DEV_CONTAINER_REGISTRY_PASSWORD }}
      - name: Log into production container registry
        uses: docker/login-action@v1
        with:
          registry: synthetik.azurecr.io
          username: synthetik
          password: ${{ secrets.PROD_CONTAINER_REGISTRY_PASSWORD }}
      - run: echo ${{ inputs.labels }}
      # - name: Run Azure Command
      #   uses: azure/CLI@v1
      #   with:
      #     inlineScript: |
      #       az extension add --name azure-iot
      #       az iot hub module-identity list -d jacob-test-agx -l "HostName=uci-cloud-coxIotHub.azure-devices.net;SharedAccessKeyName=github-action;SharedAccessKey=g/b2B2QQ8bvEn5ypCrNo2L/qwngN+/nNLz4dXo9wRdo="

      