name: Deploy IoT Edge Module

on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string

jobs:
  prepare-deployment-name:
    name: Create Deployment Name
    runs-on: ubuntu-latest
    outputs:
      deploymentName: ${{ steps.create-deployment-name.outputs.deploymentName }}
    steps:
      - name: Create Deployment Name
        id: create-deployment-name
        run: |
          deploymentName="${{inputs.module}}-PR_${{github.event.pull_request.number}}"
          #* set name to lowercase, replace slash with underscore
          formattedName=$(echo $deploymentName | tr '/' '_' | tr '[:upper:]' '[:lower:]')
          echo "::set-output name=deploymentName::$formattedName"

  find-assigned-devices:
    runs-on: ubuntu-latest
    steps:
    - name: Get Assigned Test Devices
      id: get-assigned-test-devices
      run: |
        labels="${{ join(github.event.pull_request.labels.*.name, ', ') }}"
        devices=()
        for label in ${labels//,/ } #* split labels by comma and space, iterate over
        do
          if [[ "$label" == "dev_id"* ]] #* if label is for a device
          then
            device=$(echo $label | cut -d ':' -f 2) #* split by colon and get the second part
            devices+=(deviceId=\'$device\' OR ) #* add to array with 'or' for IoT deployment
          fi
        done
        unset devices[-1] || echo 0
        echo "::set-output name=devices::$(echo ${devices[@]})"
    outputs:
      devices: ${{ steps.get-assigned-test-devices.outputs.devices }}

  update-deployed-devices:
    name: Update Devices to Deploy To
    runs-on: ubuntu-latest
    needs:
      - find-assigned-devices
      - prepare-deployment-name
    steps:
    - run: |
        az extension add --name azure-iot
        az iot edge deployment update -d "${{ needs.prepare-deployment-name.outputs.deploymentName }}" -l "${{ secrets.SYNTHETIKDEV_UVIS_IOT_HUB_CSTRING }}" --set targetCondition="${{ needs.find-assigned-devices.outputs.devices }}"
