name: IoT Module Development

on:
  workflow_call:

jobs:
  versioning:
    name: Short SHA Versioning
    runs-on: self-hosted
    steps:
    - name: Get Short SHA
      id: get-short-sha
      uses: synthetik-technologies/actions/composites/sha-versioning@2-separate-versioning-and-docker-building
    outputs:
      version: ${{ steps.get-short-sha.outputs.version }}