name: Docker Image CI

on: workflow_call

jobs:

  sem-ver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: "x64"
          cache: pip
      - name: Log into git
        run: |
          git config --global user.name jdh313
          git config --global user.email hoehler@synthetik-technologies.com
      - run: |
          pip install git+https://github.com/jacksbox/python-semantic-release@feature/prerelease-reworked
          semantic-release --prerelease version
          vers=$(semantic-release print-version)
          echo $vers